//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UoN.ExpressiveAnnotations.Net8Sample {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UoN.ExpressiveAnnotations.Net8Sample.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address format should start from &apos;Street&apos; prefix. ähnelt.
        /// </summary>
        public static string AddressDetailsFormatInvalid {
            get {
                return ResourceManager.GetString("AddressDetailsFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provide more characters than &apos;{StreetPrefix}&apos; prefix only... ähnelt.
        /// </summary>
        public static string AddressDetailsTooShort {
            get {
                return ResourceManager.GetString("AddressDetailsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Age ähnelt.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agree for contact ähnelt.
        /// </summary>
        public static string AgreeForContact {
            get {
                return ResourceManager.GetString("AgreeForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to authorize us to contact you. ähnelt.
        /// </summary>
        public static string AgreeForContactRequired {
            get {
                return ResourceManager.GetString("AgreeForContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assertion for {0} field is not satisfied by the following logic: {1} ähnelt.
        /// </summary>
        public static string AssertionNotSatisfied {
            get {
                return ResourceManager.GetString("AssertionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I am aware of the possible risks ähnelt.
        /// </summary>
        public static string AwareOfTheRisks {
            get {
                return ResourceManager.GetString("AwareOfTheRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are required to agree that you are aware of the risks of travel. ähnelt.
        /// </summary>
        public static string AwareOfTheRisksRequired {
            get {
                return ResourceManager.GetString("AwareOfTheRisksRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blood type ähnelt.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown blood type... ähnelt.
        /// </summary>
        public static string BloodTypeInvalid {
            get {
                return ResourceManager.GetString("BloodTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blood type is required if you do extreme sports, or if you do any type of sport and plan to go abroad. ähnelt.
        /// </summary>
        public static string BloodTypeRequired {
            get {
                return ResourceManager.GetString("BloodTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die China ähnelt.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assertion for {0} field is not satisfied - text &apos;{コメント}&apos; is too short. ähnelt.
        /// </summary>
        public static string CustomizedAssertThatDefaultError {
            get {
                return ResourceManager.GetString("CustomizedAssertThatDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {0} field is conditionally required. ähnelt.
        /// </summary>
        public static string CustomizedRequiredIfDefaultError {
            get {
                return ResourceManager.GetString("CustomizedRequiredIfDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only digits are accepted. ähnelt.
        /// </summary>
        public static string DigitsOnlyAccepted {
            get {
                return ResourceManager.GetString("DigitsOnlyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donation [USD] ähnelt.
        /// </summary>
        public static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provided e-mail address has invalid format. ähnelt.
        /// </summary>
        public static string EmailFormatInvalid {
            get {
                return ResourceManager.GetString("EmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not enter any contact information. At least e-mail or phone should be provided. ähnelt.
        /// </summary>
        public static string EmailOrPhoneRequired {
            get {
                return ResourceManager.GetString("EmailOrPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extreme ähnelt.
        /// </summary>
        public static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {0} field is required by the following logic: {1} ähnelt.
        /// </summary>
        public static string FieldConditionallyRequired {
            get {
                return ResourceManager.GetString("FieldConditionallyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {0} field is required. ähnelt.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flight identifier ähnelt.
        /// </summary>
        public static string FlightId {
            get {
                return ResourceManager.GetString("FlightId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provided flight identifier is invalid. ähnelt.
        /// </summary>
        public static string FlightIdentifierInvalid {
            get {
                return ResourceManager.GetString("FlightIdentifierInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die France ähnelt.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We are afraid that going back to the past is not an option nowadays. ähnelt.
        /// </summary>
        public static string FutureDateRequired {
            get {
                return ResourceManager.GetString("FutureDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Germany ähnelt.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I am going abroad ähnelt.
        /// </summary>
        public static string GoAbroad {
            get {
                return ResourceManager.GetString("GoAbroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High ähnelt.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home address ähnelt.
        /// </summary>
        public static string HomeAddress {
            get {
                return ResourceManager.GetString("HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification ähnelt.
        /// </summary>
        public static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification value ähnelt.
        /// </summary>
        public static string IdentificationValue {
            get {
                return ResourceManager.GetString("IdentificationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID number invalid (3 letters and 6 digits expected) ähnelt.
        /// </summary>
        public static string IDNumberInvalid {
            get {
                return ResourceManager.GetString("IDNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID number missing ähnelt.
        /// </summary>
        public static string IDNumberMissing {
            get {
                return ResourceManager.GetString("IDNumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Immediate contact ähnelt.
        /// </summary>
        public static string ImmediateContact {
            get {
                return ResourceManager.GetString("ImmediateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shall we contact immidiately? ähnelt.
        /// </summary>
        public static string ImmediateContactRequired {
            get {
                return ResourceManager.GetString("ImmediateContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Israel ähnelt.
        /// </summary>
        public static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Japan ähnelt.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Just a few characters more... ähnelt.
        /// </summary>
        public static string JustAFewCharsMore {
            get {
                return ResourceManager.GetString("JustAFewCharsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Known languages ähnelt.
        /// </summary>
        public static string KnownLanguages {
            get {
                return ResourceManager.GetString("KnownLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than one language must be known. ähnelt.
        /// </summary>
        public static string LanguagesSelectionInsufficient {
            get {
                return ResourceManager.GetString("LanguagesSelectionInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest suggested return ähnelt.
        /// </summary>
        public static string LatestSuggestedReturnDate {
            get {
                return ResourceManager.GetString("LatestSuggestedReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low ähnelt.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The period of stay should be at least a week. ähnelt.
        /// </summary>
        public static string MoreThanAWeekRequired {
            get {
                return ResourceManager.GetString("MoreThanAWeekRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next country ähnelt.
        /// </summary>
        public static string NextCountry {
            get {
                return ResourceManager.GetString("NextCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The period of stay should be less than a year. ähnelt.
        /// </summary>
        public static string NoMoreThanAYear {
            get {
                return ResourceManager.GetString("NoMoreThanAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More separate donations are required: if {GoAbroad:N} field is checked - at least 3, otherwise - at least 2. ähnelt.
        /// </summary>
        public static string NotEnoughDonations {
            get {
                return ResourceManager.GetString("NotEnoughDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Office address ähnelt.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passport ähnelt.
        /// </summary>
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passport number invalid (2 letters and 7 digits expected) ähnelt.
        /// </summary>
        public static string PassportNumberInvalid {
            get {
                return ResourceManager.GetString("PassportNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passport number missing ähnelt.
        /// </summary>
        public static string PassportNumberMissing {
            get {
                return ResourceManager.GetString("PassportNumberMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poland ähnelt.
        /// </summary>
        public static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Political stability ähnelt.
        /// </summary>
        public static string PoliticalStability {
            get {
                return ResourceManager.GetString("PoliticalStability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone number should contain from 9 to 15 digits. ähnelt.
        /// </summary>
        public static string RangeViolated {
            get {
                return ResourceManager.GetString("RangeViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reasons for such a long travel ähnelt.
        /// </summary>
        public static string ReasonForLongTravel {
            get {
                return ResourceManager.GetString("ReasonForLongTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you plan to stay abroad longer than one month from now, write down your reasons. ähnelt.
        /// </summary>
        public static string ReasonForLongTravelRequired {
            get {
                return ResourceManager.GetString("ReasonForLongTravelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reasons for travel ähnelt.
        /// </summary>
        public static string ReasonForTravel {
            get {
                return ResourceManager.GetString("ReasonForTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you plan to go abroad and you are between 25 and 55 or plan to visit the same foreign country twice, write down your reasons. ähnelt.
        /// </summary>
        public static string ReasonForTravelRequired {
            get {
                return ResourceManager.GetString("ReasonForTravelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you are under 18 (indicated {Age} in {Age:N} field, yes - {Age:N} {Age}), give us a reason of your travel no matter where you go (BTW.  {Country}... nice choice). ähnelt.
        /// </summary>
        public static string ReasonForTravelRequiredForYouth {
            get {
                return ResourceManager.GetString("ReasonForTravelRequiredForYouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Return date ähnelt.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, it is not a question about John&apos;s cat nor Simon&apos;s cat. ähnelt.
        /// </summary>
        public static string SecretAnswerDetected {
            get {
                return ResourceManager.GetString("SecretAnswerDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select currency. ähnelt.
        /// </summary>
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a date ähnelt.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I agree for contact ähnelt.
        /// </summary>
        public static string SpamAllowed {
            get {
                return ResourceManager.GetString("SpamAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I do not agree for contact ähnelt.
        /// </summary>
        public static string SpamForbidden {
            get {
                return ResourceManager.GetString("SpamForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sports you like the most ähnelt.
        /// </summary>
        public static string SportType {
            get {
                return ResourceManager.GetString("SportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street ähnelt.
        /// </summary>
        public static string StreetPrefix {
            get {
                return ResourceManager.GetString("StreetPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uncertain ähnelt.
        /// </summary>
        public static string Uncertain {
            get {
                return ResourceManager.GetString("Uncertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
